### PR TITLE
added two linkedin/Instagram profiles with icons and centerd

### PR DESCRIPTION
**Pull request by karthickbharathi1**

### CODE REVIEW

**Comment by karthickbharathi1** [comment]
Hey @onlykingKD. I have added tow LinkedIn profiles with icons and centered the links.

**Comment by onlykingKD** [comment]
> Hey @onlykingKD. I have added tow LinkedIn profiles with icons and centered the links.

Also remove google icon and Twitter icon 

And add one more Instagram icon.
Both Instagram links should point to below Instagram profiles

manavgoyal111
onlykingkd

**Comment by karthickbharathi1** [comment]
Hey @onlykingKD. I have removed the google and twitter icons and added another Instagram icon which goes to the profile included.

**Comment by onlykingKD** [comment]
Thanks for the contribution.

**Pull request merged**
