### PR TITLE
Added sort buttons and fixed filter bugs

### PR DESCRIPTION
**Pull request by prane-eth**

### CODE REVIEW

**Comment by prane-eth** [comment]
This pull request is to solve the issue #8 
https://github.com/manavgoyal111/placement-2023/issues/8

**Comment by onlykingKD** [comment]
@prane-eth excellent work. It works perfectly fine.
can you please fix the UI of filters a little more?
Like add proper margin/padding and proper coloring. It looks clumsy now.

**Comment by prane-eth** [comment]
> @prane-eth excellent work. It works perfectly fine. can you please fix the UI of filters a little more? Like add proper margin/padding and proper coloring. It looks clumsy now.

It is done now. You can check preview in the same link.

**Comment by onlykingKD** [comment]
@prane-eth THANKS for implementing this important feature

**Pull request merged**
